name       : x2goserver
version    : 4.0.1.20
release    : 7
source     :
    - https://code.x2go.org/releases/source/x2goserver/x2goserver-4.0.1.20.tar.gz : f8bf48e1c8995bd5a7cde6de1c006fdb77f2bae6c4b82e6b7b985a8f00a3dad9
license    : GPL-2.0
component  : network.util
summary    : x2go remote desktop server
description: |
    X2Go is an open source remote desktop software for Linux that uses the NX technology protocol. X2Go gives remote access to the Linux graphical user interface. It can also be used to access PC desktops. It provides secure remote sessions via ssh.
# This ensures x2gouser user and group exists during install to set permissions
builddeps  :
    - x2goserver
rundeps    :
    - nx-libs
    - openssh-server
    - perl-capture-tiny
    - perl-config-simple
    - perl-dbd-sqlite
    - perl-file-basedir
    - perl-file-which
    - pwgen
    - xwininfo
setup      : |
    %apply_patches
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    install -D -m 00644 x2goserver.service $installdir/usr/lib64/systemd/system/x2goserver.service
    install -D -m 00644 $pkgfiles/x2goserver.sysusers $installdir/usr/lib64/sysusers.d/x2goserver.conf
    install -D -m 00644 $pkgfiles/x2goserver.tmpfiles $installdir/usr/lib64/tmpfiles.d/x2goserver.conf
